#!/usr/bin/env python3
"""Embeds the high-res HUD textures (port/assets/hud, made by
tools/hud_assets.py) in the game as C data:

    python tools/embed_assets.py OUTPUT.c
    python tools/embed_assets.py --fonts OUTPUT.c

writes OUTPUT.c with each PNG and the bitmap it stands for (its tag, index
and the checksum of its pixels, from port/assets/hud/layout.json), as
port/linux/src/hud_hires.h declares them; with --fonts, the overlay's fonts
(port/linux/ui/fonts), as port/linux/src/posix_ui_font.c declares them.

The builds generate them
(hud_assets_build, called by tools/linux_build.py, windows_build.py and
android_build.py), so the PNGs are the committed source and Android needs
no files beside its guest image.

The data are 32-bit words, not bytes: the Android build passes the guest's
assembly through tools/android_asm_convert.py, which rewrites identifiers in
operands and would garble a long .ascii string of binary data.
"""

import json
import struct
import sys
from pathlib import Path
from typing import Any, List

ROOT = Path(__file__).resolve().parent.parent
HUD_ASSETS = Path("port/assets/hud")
LAYOUT = HUD_ASSETS / "layout.json"
PNG_SIGNATURE = b"\x89PNG\r\n\x1a\n"
# the overlay's fonts (the game browser's; posix_ui_font.c), in its order
UI_FONTS = Path("port/linux/ui/fonts")
UI_FONT_FILES = ["NotoSans-Regular.ttf", "NotoSans-Bold.ttf", "input_xbox.ttf", "input_playstation.ttf",
                 "input_nintendo.ttf", "input_keyboard.ttf"]


def hud_asset_inputs() -> List[Path]:
    """The files the generated source is made from."""
    if not (ROOT / LAYOUT).is_file():
        return []
    assets = json.loads((ROOT / LAYOUT).read_text())["assets"]
    return [LAYOUT, *(HUD_ASSETS / f"{asset['name']}.png" for asset in assets)]


def hud_configure_inputs() -> List[Path]:
    """What configure.py is run again for: the list of assets (and the folder,
    for PNGs added or removed), not each PNG, which a change of the list may
    rename or remove."""
    return [HUD_ASSETS, LAYOUT] if (ROOT / LAYOUT).is_file() else []


def hud_assets_build(n: Any, prefix: str, output: Path) -> List[Path]:
    """Emits the rule that generates output; returns [output], or nothing
    when there are no assets."""
    inputs = hud_asset_inputs()
    if not inputs:
        return []
    n.rule(
        name=f"{prefix}_embed_assets",
        command="$python tools/embed_assets.py $out",
        description=f"{prefix.upper()} EMBED $out",
    )
    n.build(outputs=output, rule=f"{prefix}_embed_assets", implicit=[Path("tools/embed_assets.py"), *inputs])
    return [output]


def ui_fonts_build(n: Any, prefix: str, output: Path, sln: Any) -> List[Path]:
    """Emits the rule that generates the overlay's fonts' source (with the
    game browser); returns [output], or nothing"""
    if not getattr(sln, "game_browser", False):
        return []
    n.rule(
        name=f"{prefix}_embed_fonts",
        command="$python tools/embed_assets.py --fonts $out",
        description=f"{prefix.upper()} EMBED $out",
    )
    n.build(outputs=output, rule=f"{prefix}_embed_fonts",
            implicit=[Path("tools/embed_assets.py"), *(UI_FONTS / name for name in UI_FONT_FILES)])
    return [output]


def words(data: bytes) -> List[str]:
    """data as lines of 32-bit words (little-endian, padded with zeros)"""
    padded = data + b"\0" * (-len(data) % 4)
    values = struct.unpack(f"<{len(padded) // 4}I", padded)
    return ["\t" + ", ".join(f"0x{word:08x}" for word in values[start:start + 8]) + ","
            for start in range(0, len(values), 8)]


def write(output: Path, lines: List[str]) -> None:
    output.parent.mkdir(parents=True, exist_ok=True)
    text = "\n".join(lines) + "\n"
    if not output.is_file() or output.read_text() != text:
        output.write_text(text)


def fonts(output: Path) -> None:
    lines = [
        "/* generated by tools/embed_assets.py --fonts from port/linux/ui/fonts: do not edit */",
        "",
    ]
    for index, name in enumerate(UI_FONT_FILES):
        lines.append(f"static const unsigned int font{index}[] = {{")
        lines.extend(words((ROOT / UI_FONTS / name).read_bytes()))
        lines.append("};")
        lines.append("")
    lines.append("/* (posix_ui_font.c's: each font's data, as words) */")
    lines.append(f"const unsigned int *const ui_font_files[{len(UI_FONT_FILES)}] =")
    lines.append("{")
    lines.append("\t" + ", ".join(f"font{index}" for index in range(len(UI_FONT_FILES))) + ",")
    lines.append("};")
    write(output, lines)


def png_size(data: bytes, name: str) -> tuple:
    """The width and height of an 8-bit RGBA, non-interlaced PNG (the only
    kind port/linux/src/hud_hires.c reads)."""
    if data[:8] != PNG_SIGNATURE or data[12:16] != b"IHDR":
        sys.exit(f"{name}: not a PNG")
    width, height, depth, colour, _, _, interlace = struct.unpack(">IIBBBBB", data[16:29])
    if depth != 8 or colour != 6 or interlace != 0:
        sys.exit(f"{name}: must be 8-bit RGBA and not interlaced")
    return width, height


def main() -> None:
    if len(sys.argv) == 3 and sys.argv[1] == "--fonts":
        fonts(Path(sys.argv[2]))
        return
    if len(sys.argv) != 2:
        sys.exit("usage: embed_assets.py [--fonts] OUTPUT.c")
    layout = json.loads((ROOT / LAYOUT).read_text())
    lines = [
        "/* generated by tools/embed_assets.py from port/assets/hud: do not edit */",
        "",
        '#include "hud_hires.h"',
        "",
    ]
    table = []
    for index, asset in enumerate(layout["assets"]):
        name = f"{asset['name']}.png"
        data = (ROOT / HUD_ASSETS / name).read_bytes()
        width, height = png_size(data, name)
        scale = asset["scale"]
        if (width, height) != (asset["width"] * scale, asset["height"] * scale):
            sys.exit(f"{name}: {width}x{height}, not {scale}x its bitmap's {asset['width']}x{asset['height']}")
        lines.append(f"static const unsigned int asset{index}[] = {{")
        lines.extend(words(data))
        lines.append("};")
        lines.append("")
        tag = asset["tag"].replace("\\", "\\\\")
        coverage = int(any(cell["kind"] == "meter" for cell in asset["cells"]))
        table.append(f'\t{{ "{tag}", {asset["bitmap"]}, {width}, {height}, 0x{asset["crc"]:08x}u, {coverage}, '
                     f'asset{index}, {len(data)} }},')
    lines.append("const struct hud_hires_embedded hud_hires_embedded[] =")
    lines.append("{")
    lines.extend(table)
    lines.append("};")
    lines.append(f"const unsigned int hud_hires_embedded_count = {len(table)};")
    write(Path(sys.argv[1]), lines)


if __name__ == "__main__":
    main()
